require "lib/au/vim"
require "lib/vim/defaults"
require "lib/vim/netrw"
require "lib/vim/bindings"
require "lib/plugins"
require "lib/tools/search"
require "lib/lsp"
require "lib/functions/path"
require "lib/functions/line-history"
-- require "lsp"
